replicaCount: 1

image:
  repository: satishlakshmiudemy/easy_to_buy_angular
  pullPolicy: Always
  tag: "v1.0"



livenessProbe:
  failureThreshold: 4
  initialDelaySeconds: 60
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 1

serviceAccount:
  create: true

  annotations: {}

  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 9000

probes:
  enabled: true

ingress:
  enabled: false
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          backend:
            serviceName: chart-example.local
            servicePort: 80
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
